### PR TITLE
Dynamically add child routes to an existing route #1156

### PR DESCRIPTION
**Pull request by Dri4n**
Reason:
we need to add dynamic routes that are associated with a parent.

Unit Test:
router.addRoutes - from line "nested routes existing children relation".

Excuse me if this PR does not meet the guidelines, is my first PR in OpenSource.

Thanks!

### CODE REVIEW

**Comment by Dri4n** [comment]
I do not know, but I think it may also be possible to integrate the parent route according to the name of the parent route.

Thanks

**Comment by posva** [comment]
Hey, thanks for the PR. I'll need to take a deeper look, I'm not quite convinced by the API yet and would also like to make sure it works with 2-level nested children

**Comment by Dri4n** [comment]
You're right, I apologize for that ... we need to check if it can be loaded at a second level of nesting, this should be similar to how the asynchronous loading of components in a route behaves.

**Comment by Dri4n** [comment]
sorry for the delay, I have been very busy in my work

@posva  I'm not sure 100% of what I should try, I've done the following tests ...

`    let components

    router.push('/g1')
    components = router.getMatchedComponents()

    router.addRoutes([
       { path: '/e1', name: 'E1', component: { name: 'E1Component' }},
       { path: '/f1', name: 'F1', component: { name: 'F1Component' }, parent: '/e1' } // with path association
    ])

    router.addRoutes([
      { path: '/g1', name: 'G1', component: { name: 'G1Component' }, parent: 'F1' } // with name association
    ])
    components = router.getMatchedComponents()`

components return....

`[ { name: 'E1Component', _Ctor: { '0': [Object] }, inject: {} },
  { name: 'F1Component', _Ctor: { '0': [Object] }, inject: {} },
  { name: 'G1Component', _Ctor: { '0': [Object] }, inject: {} } ]`

this returns the three levels of routes, the main conditional is that the route to which you associate the daughter route must be created.

Could you give me a guide of what is looked for in its entirety when adding a route to a parent route, thanks in advance.

**Comment by posva** [comment]
No worries, I'll come back at you.

**Comment by xilibro** [comment]
great, When does  this feature released

**Comment by michaelgallaghertw** [comment]
hey @posva, I see this issue is still awaiting triage in the project, any idea when it will make it into the flow and into a version of the router?

If the API is still an open question, as I do see inconsistency myself, I would suggest it would follow the more standard `string | Location` syntax, so possibilities would include:

* `parent: '/path'`
* `parent: { path: '/path' }`
* `parent: { name: 'name' }`

If it is agreed to change this, I have no problem doing it myself, but @Dri4n has done the work so far, so he certainly has first call.

**Comment by posva** [comment]
I think it's reasonable to force the usage of a name in a route for this

```js
router.addRoutes('name', [...])
router.addRoutes([...])
```

**Comment by KeithMo0425** [comment]
@posva 
Hi,
When will this feature be released?
We are in urgent need of this new feature, there are other way?

**Comment by posva** [comment]
Unfortunately, I don't have any estimate for this FR

**Comment by piotrek-horodenski** [comment]
This is sad, it would be great to see it in the next release.

**Comment by AGPDev** [comment]
I need much this too, thanks @Dri4n for work on this, unfortunately after you time in this feature and almost one year not released yet :/

**Comment by lilywang711** [comment]
When will this feature be released?
We are in urgent need of this new feature, there are other way?

**Comment by piotrek-horodenski** [comment]
seems like a wistle in a forrest


śr., 23 sty 2019 o 04:52 lily wang <notifications@github.com> napisał(a):

**Comment by zh-rocco** [comment]
Expecting.

**Comment by jahsome** [comment]
Are the any recommended workarounds or third-party libraries to utilize while this PR is up for review?

**Comment by yovchev** [comment]
@jake-harris before we get this released if you need simple work around you can store the entire route with the childrens in a varible and when you need to push new child update the varible childrens array and pass the entire route tree to the router.addRoutes() and this will overide any existing route configuration. Have a look at this example : https://yovchev.github.io/vue-dynamic-routes/ 
[Example Repository](https://github.com/yovchev/vue-dynamic-routes)

```javascript
// src/views/NotFound.vue

import { DynamicRoutes } from '@/routes'

export default {
    methods: {
        loadMissingRoutes() {
            // Load missing route
            DynamicRoutes.children.push({
                name: 'about',
                path: 'about',
                component: () => import(/* webpackChunkName: "about" */ '@/views/About.vue')
            })
            // Update the routes
            this.$router.addRoutes([DynamicRoutes])
        }
    }
}
```

**Comment by jahsome** [comment]
@yovchev - That's clever, I think that should get me where I need to be. Thanks!

**Comment by vuchan** [comment]
If after review it is right, pls merge this feature, hum...., it is very useful feature.

**Comment by yofr4nk** [comment]
It would be nice if we have this release. Great work

**Comment by jordoreed** [comment]
+1 for this. We've got an ugly workaround that this would clear up. Thanks

**Comment by posva** [comment]
@Dri4n Sorry for the delay! Could you make the changes so adding routes to a parent requires a name: 

```js
router.addRoutes('name', [...])
router.addRoutes([...])
```

**Comment by posva** [comment]
Thanks, at the end this was added at ca80c44

**Pull request closed without merging**
