### PR TITLE
Handle iOS DOM Exception 18 #564

### PR DESCRIPTION
**Pull request by Awea**

### CODE REVIEW

**Comment by LinusBorg** [comment]
Can you comment your changes a bit, especially how your changed prevent this iOS Bug from happening?

**Comment by Awea** [comment]
@LinusBorg Sure but it doesn't prevent it, it handle it. I'll add a comment.

**Comment by Awea** [comment]
@LinusBorg Is it more clear ? :)

**Comment by yyx990803** [comment]
Thanks, can you remove the change to `dist`? That folder is only updated on releases.

**Comment by Awea** [comment]
@yyx990803 Oups, sorry for that.

**Comment by Awea** [comment]
@yyx990803 Should I redo a well formated pull request or this is cover by something else ?

**Pull request closed without merging**
