### PR TITLE
[docs:korean] Migrate git-book to vuepress

### PR DESCRIPTION
**Pull request by ChangJoo-Park**
- Add Korean to config.js
- Translate README.md in root 
- Translate README.md in guide
- Change word transition in Korean (전환 -> 트랜지션) same as Vue.js korean docs

### CODE REVIEW

**Comment by ChangJoo-Park** [comment]
It has problem with `/kr/api`. I am going to fix it.

**Comment by ChangJoo-Park** [comment]
Fix API docs for vuepress has done.

**Review by usolkim — APPROVED** [review]

**Comment by posva** [comment]
@ChangJoo-Park is it ready to merge?

**Comment by ChangJoo-Park** [comment]
@posva Sure :)

**Comment by ChangJoo-Park** [comment]
thanks @kazupon :+1:

**Pull request merged**
