### PR TITLE
Reports about the build needed for the demo work

### PR DESCRIPTION
**Pull request by vinicius73**

### CODE REVIEW

**Comment by posva** [comment]
I don't think this is necessary since there's an example at the bottom of the page

**Comment by vinicius73** [comment]
This PR is based on feedback from my local community. More than one time they had doubts with this situation.

**Comment by posva** [comment]
I'd rather add global note at the beginning of the guide: http://router.vuejs.org/en/essentials/getting-started.html

> All examples will be using the standalone version of vue to make template parsing possible

@fnlctrl What are your thoughts on this?

**Comment by fnlctrl** [comment]
Yeah, that should be enough.

**Comment by posva** [comment]
@vinicius73 Do you find that statement clear enough?

**Comment by vinicius73** [comment]
yes @posva is much better so I will update.

**Review by posva — APPROVED** [review]
Ping @fnlctrl

**Review by fnlctrl — APPROVED** [review]

**Pull request merged**
