### PR TITLE
[KR] Update named-routes.md

### PR DESCRIPTION
**Pull request by jyqry**

### CODE REVIEW

**Review by kazupon — COMMENTED** [review]
/ping @ChangJoo-Park 
Can you review please?

**Review by ChangJoo-Park — APPROVED** [review]
이다 is informal

입니다 is formal verb

**Comment by ChangJoo-Park** [comment]
@kazupon 
Please merge this PR

@jyqry 감사합니다

**Comment by kazupon** [comment]
@ChangJoo-Park 
Thanks!

**Pull request merged**
