### PR TITLE
feat(link): add 'exact-path' matching option

### PR DESCRIPTION
**Pull request by emanuelmutschlechner**
Improves unfinished pull request #2070 and closes issue #2040

### CODE REVIEW

**Comment by posva** [comment]
Thanks! I need to check some things first about the API. I'll come back at you 😅

**Comment by cvharris** [comment]
It looks like this was not touched upon in awhile, could it be merged soon?

One great use case for this is when individual components are not aware of the current route or need to add extra logic to become aware of it. Since `<router-link>` already has logic to determine if the current path matches the link, this PR would help tailor the exact matching to the important path and ignore query params and hashes.

Hoping it makes it in soon! 😅

**Comment by JuroOravec** [comment]
Any updates on this?

**Comment by posva** [comment]
Thanks! This was partially merged at cbb552c946af4ff0946e5e2f0091c8877850befd

**Pull request closed without merging**
