### PR TITLE
fix(router-view): add condition to see whether the tree is inactive (fix #2552)

### LINKED ISSUE #2552: nested router-view renders incorrect component with wrapping keep-alive at root
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/zrh122/vmopsbeh/](https://jsfiddle.net/zrh122/vmopsbeh/)

### Steps to reproduce
* click index child1
* click index child2
* click home
* click index child1

### What is expected?
index child1 component

### What is actually happening?
index child2 component

### PR DESCRIPTION
**Pull request by zrh122**
close #2552

### CODE REVIEW

**Comment by posva** [comment]
Thanks! Could you add a test case for this? e2e should be easier for the moment for this one

**Comment by zrh122** [comment]
> Thanks! Could you add a test case for this? e2e should be easier for the moment for this one

Yes, i will

**Comment by zrh122** [comment]
@posva , e2e test added.

**Review by posva — APPROVED** [review]
Thanks! I will do some minor modifications locally

**Pull request merged**
