### PR TITLE
Handle Promise rejection in guards (fix #2833)

### LINKED ISSUE #2833: Handle Promise rejection in guards
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/orzwg537/](https://jsfiddle.net/orzwg537/)

### Steps to reproduce
Run the fiddle and look in console

### What is expected?
a message saying error caught

### What is actually happening?
There is an Unhandled Promise rejection instead

---
Currently, errors thrown in guards are caught by router.onError but Promises rejections (or error thrown in an `async` function) are not caught. This should be handled in all the other guards as well. To handle them right now it is possible by passing the error to `next`:

```
try {
  await fetchdata()
} catch (error) {
  next(error)
}
```

### PR DESCRIPTION
**Pull request by oleksiikhr**
#2833

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!
However, we don't use babel to transpile the lib, so this won't work (it is used with tests). Could you find a version without adding the babel plugin dependency?
Can you also add the tests for the others navigation guards, so they are all covered? beforeEnter, beforeRouteEnter, beforeRouteUpdate
Also, could you please add back the template for the PR? It helps us to organise things

Thanks

**Comment by oleksiikhr** [comment]
Very interesting, solved without a library :)

> Also, could you please add back the template for the PR? It helps us to organise things

What is a template?

**Comment by posva** [comment]
Hey! I realized you closed the issue. Did something happen? Maybe it was closed by accident?

Eduardo San Martin Morote

**Comment by oleksiikhr** [comment]
I studied this code, found 2 places (`hook`) where **Promise** can be accepted (`beforeEach`, `afterEach`):

https://github.com/vuejs/vue-router/pull/2838/files#diff-feafce5e816936212eccd6808c5421a6R123
https://github.com/vuejs/vue-router/pull/2838/files#diff-feafce5e816936212eccd6808c5421a6R185

And if in the first case the execution of the code, the sequence itself does not change, in the second case it is not so (R185).

If we take into account that everything happens through callbacks, then in the function `confirmTransition`, I also need to transfer to `onComplete` the callback also the `this._abort` function. In the **abstract.js**, **base.js** files, receive and transmit the `updateRoute` function.

In general, I do not like it, I understand that most likely I need to wrap parts of the code in **Promise**, do consistent error handling and not break the original logic.

Since this PR has errors in logic, I decided to close it, so that suddenly due to inactivity, they would not begin to accept it :)

**Comment by posva** [comment]
Thanks for the explanation. I wanted to make sure it wasn't an accident :)
With current codebase it's a bit harder to implement indeed

**Pull request closed without merging**
