### PR TITLE
feat: useRoute and useRouter

### LINKED ISSUE #3760: [Feature Request] Add support for Vue 2.7
### What problem does this feature solve?
As composition api has been incoporated in vue 2.7, `vue-router` should provide `useRoute` and `useRouter` to enable router usage in `<setup script>`.

### What does the proposed API look like?
```
const router = useRouter()
router.push(...)
```
Just like in Vue3

### PR DESCRIPTION
**Pull request by posva**
Close #3760

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@posva Can you update rollup build output for `composables.js`?

**Comment by posva** [comment]
yes! this is still a wip PR

**Comment by xiaoxiangmoe** [comment]
@posva ❤️ ok, please ping me after you finish. I'll add types for it.

**Comment by posva** [comment]
@xiaoxiangmoe you can now, if you want. I think useLink can wait

**Pull request merged**
