### PR TITLE
feat(history): allow same route navigation

### PR DESCRIPTION
**Pull request by boycce**
To get the component to build a fresh instance you need to add a key attribute i.e `<router-view :key="$route.id"></router-view>`. Regardless the vue-router hooks still fire when reloading.

Issue: #974 
Related: #2957 #2430

### CODE REVIEW

**Comment by pedzed** [comment]
While this is not yet implemented, how could you force a refresh when the `query` changes in `<router-link>`?

**Comment by n123456789k** [comment]
@pedzed you can do a watch on the route

**Comment by pedzed** [comment]
@narwy Can you give an example? Or refer me to some reading material?

Thanks.

**Comment by posva** [comment]
Thank you but this doesn't implement #974 

Removing the duplicated navigation would be a breaking change, so the change is v4 only (per https://github.com/vuejs/rfcs/pull/150)

**Pull request closed without merging**
