### PR TITLE
Add public Router#resolve method as per #831.

### PR DESCRIPTION
**Pull request by hogart**
Necessary docs, tests, typings. Fixes per code review.

Sorry for the mess, my git-fu isn't good enough.

### CODE REVIEW

**Comment by LinusBorg** [comment]
Note: continuation of PR #877

**Review by LinusBorg — APPROVED** [review]
LGTM

**Comment by hogart** [comment]
Any thoughts, feedback, suggestions?

**Review by fnlctrl — APPROVED** [review]

**Comment by LinusBorg** [comment]
@hogart We will definitely merge this, no worries. And thanks for the contribution.

But it depends a bit on Evan to decide when the next release will be.

**Comment by hogart** [comment]
Glad to be useful, it was interesting experience. And thanks everyone for input and feedback:)

**Comment by yyx990803** [comment]
👍

**Pull request merged**
