### PR TITLE
[Just Merge Me][Community Translation] Russian Translation Update

### PR DESCRIPTION
**Pull request by gbezyuk**

### CODE REVIEW

**Review by kazupon — COMMENTED** [review]
/ping @simplesmiler

**Review by simplesmiler — APPROVED** [review]
LGTM!

**Comment by blake-newman** [comment]
@gbezyuk Looks like some files have become out of date

**Comment by gbezyuk** [comment]
@blake-newman thank you for noticing, we'll fix it
@Alex-Sokolov, bro please take a look

**Comment by Alex-Sokolov** [comment]
Files looks good. Don't know why there are conflicts

**Comment by gbezyuk** [comment]
@blake-newman all conflicts have been resolved

**Comment by posva** [comment]
Thanks @gbezyuk

**Pull request merged**
