### PR TITLE
Add feature external routes

### PR DESCRIPTION
**Pull request by emanuelmutschlechner**
This commit adds support for external routes in `routes` of the router.

Feature request:
#1280

Live demo:
https://7496x53w10.codesandbox.io/

Interactive example:
https://codesandbox.io/s/7496x53w10

### CODE REVIEW

**Comment by posva** [comment]
Hello, really appreciate your efforts on this. It's not exactly what I was thinking about. I'll come back at you as soon as I can

**Comment by teucer** [comment]
@posva could you please tell the ETA on this?

**Comment by posva** [comment]
At the moment there is none. This is a bit different from what I would expect about external links

**Comment by emanuelmutschlechner** [comment]
@posva would you mind sharing your expectations/idea/proposed api?

**Comment by posva** [comment]
Router link to make an external link passed as the to prop to work with nothing else

**Comment by posva** [comment]
Closing due to inactivity. Let's hold on implementing this for the moment

**Pull request closed without merging**
