### PR TITLE
[Docs] Use ternary operator in example

### PR DESCRIPTION
**Pull request by parkourben99**

### CODE REVIEW

**Review by kazupon — COMMENTED** [review]
Thanks!

If it's possible, we would be grateful if you could update the other langs (`zh`, `ja`, and more). 🙏

**Comment by posva** [comment]
I'm actually not that convinced for the example to use a ternary here. Even though  I would use it in my projects, I think it's easier to learn using a plain if/else @chrisvfritz WDYT?

**Comment by parkourben99** [comment]
Shouldn't we be showing best practice examples?

**Comment by chrisvfritz** [comment]
I agree with @posva that this just makes the examples more difficult to read for many people. For those who are very familiar and comfortable with ternaries, they'll already know how to convert this into a ternary. For people who aren't, this more verbose version works just as well and still might be preferred to the ternary for readability.

**Pull request closed without merging**
