### PR TITLE
Send props not defined on the route component in $attrs. Fixes #1695.

### LINKED ISSUE #1695: Pass down route props to $attrs
### Version
2.7.0

### Reproduction link
[https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg](https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg)

### Steps to reproduce
Click on the different links

### What is expected?
Passing props in the route object:

```js
{ path: '/', component: Hello, props: { name: 'world' }},
```

should appear in `$attrs` as long as `name` is not declared as a prop in `Hello.vue`

### What is actually happening?
no prop

---
moved from https://github.com/vuejs/vue/issues/6426

### PR DESCRIPTION
**Pull request by lbogdan**
Fixes https://github.com/vuejs/vue-router/issues/1695.

### CODE REVIEW

**Comment by lbogdan** [comment]
Hm, any idea why is the test failing? _It works on my machine™_:
```
 √ Testing if element <li a> has count: 5
...
 √ Testing if the URL equals "http://localhost:8080/route-props/attrs".
 √ Testing if element <.hello> contains text: "Hello attrs".
```

**Comment by LinusBorg** [comment]
probably because nightwatch/phantomJS is a nightmre sometimes ...

someone with access to CircleCI can usually fix it by running it without caches.

**Comment by lbogdan** [comment]
Also, that test works locally, but this one (in `test:types`) doesn't:
```
types/test/index.ts(164,7): error TS2322: Type 'Component[]' is not assignable to type 'Component'.
  Type 'Component[]' is not assignable to type 'typeof Vue'.
    Property 'prototype' is missing in type 'Component[]'.
```
Which, if I look at the code, seems to be right:
```
const Components: ComponentOptions<Vue> | typeof Vue = router.getMatchedComponents();
```
(`router.getMatchedComponents()` should return `Component[]`)

Strange?

**Comment by posva** [comment]
I rerun the tests

**Comment by lbogdan** [comment]
I see that my test passed, but as I said earlier, now `test:types` fails, even if my changes have nothing to do with TS code.

**Comment by lbogdan** [comment]
@LinusBorg @posva Any idea?

**Comment by adi518** [comment]
It's going to save us lots of code. :)

**Comment by posva** [comment]
@lbogdan No idea unfortunately 😞 
@ktsn Could you take a look, whenever you can, at the error in circle ci and see how it could be related to the small modification made 🙏 (Sorry for the inconvenience and thank you very much)

**Comment by ktsn** [comment]
@posva 
Looks like the type of `Components` variable in the test case is incorrect.

The `router.getMatchedComponent()` returns `Component[]` (alias of `(ComponentOptions<Vue> | typeof Vue | AsyncComponent)[]`) but it is annotated with `ComponentOptions<Vue> | typeof Vue` in the test case.

So replacing [this line](https://github.com/vuejs/vue-router/blob/dev/types/test/index.ts#L166) with the below would work.

```ts
const Components: (ComponentOptions<Vue> | typeof Vue)[] = router.getMatchedComponents();
```

**Comment by lbogdan** [comment]
@ktsn @posva Well, the test case is clearly incorrect, the question is why tests in other pull requests pass? 😄

**Comment by ktsn** [comment]
Looks like it's because typescript compiler version. TypeScript v2.4.0 passes the test cases but v2.4.2 doesn't. And the lockfile is updated recently. https://github.com/vuejs/vue-router/commit/76f6db96ac90811ce75402103cbbe44e275406e6

**Comment by lbogdan** [comment]
@ktsn Makes sense, then. So, how should I proceed? Should I fix that in this PR?

**Comment by lbogdan** [comment]
Hm, still https://github.com/vuejs/vue-router/blob/6d4ac757242ca700d79327459af8eccf18a18d0c/package-lock.json#L7485 uses typescript 2.4.2, and the tests pass https://circleci.com/gh/vuejs/vue-router/1570 .

**Comment by ktsn** [comment]
Maybe, it's because of CI cache?
I think we should fix the test case, anyway. I just made a PR for that. #1713

**Comment by lbogdan** [comment]
Ok, then I'll wait for it to be merged and rebase. Thanks!

**Comment by posva** [comment]
@lbogdan I merged #1713

**Comment by lbogdan** [comment]
Finally! :smile:

**Comment by lbogdan** [comment]
Ping?

**Review by posva — APPROVED** [review]
ping @yyx990803

**Comment by lbogdan** [comment]
Any news on this?

**Comment by lbogdan** [comment]
"Is there anybody out there?" :smile:

**Pull request merged**
