### PR TITLE
add this <router-link :to="-1" go>

### PR DESCRIPTION
**Pull request by mlboy**
声明式 | 编程式
-- | --
\<router-link :to="..." go\>  | router.go(-1)

### CODE REVIEW

**Comment by posva** [comment]
The point of the router-link being resolving links and displaying the actual url, this won't make sense, at least at the current state of the router. Instead, this should be use on some kind of button with `@click=$router.back()`

**Comment by JounQin** [comment]
@posva `to` is a required prop for `router-link`, and I tried `<router-link to="" @click.prevent="$router.back()">`, it does not work.

---

My temporary workaround:

```vue
<router-link to="">
  <v-icon @click="$router.back()">{{ leftSvg }}</v-icon>
</router-link>
```

**Comment by posva** [comment]
my point was: don't use a router-link if it's not going to render an `a` tag with the correct `href` attribute

**Comment by JounQin** [comment]
@posva I added an `afterEach` hook:

```ts
import { Plugin } from '@nuxt/types'
import Vue from 'vue'
import Router from 'vue-router'

Object.defineProperty(Vue.prototype, '$prevRoutePath', {
  configurable: __DEV__,
  get(this: { $router: Router }) {
    const { previousRoute } = this.$router
    return previousRoute ? previousRoute.fullPath : '/'
  },
})

const routerPlugin: Plugin = ({ app: { router } }) => {
  router.afterEach((_to, from) => {
    router.previousRoute = from
  })
}

export default routerPlugin
```

But `@click.prevent` still does not work:

```vue
<router-link :to="$prevRoutePath" @click.prevent="$router.back()">
  <v-icon>{{ leftSvg }}</v-icon>
</router-link>
```

So I still have to do like following:

```vue
<router-link :to="$prevRoutePath">
  <v-icon @click="$router.back()">{{ leftSvg }}</v-icon>
</router-link>
```

Is that a bug that `router-link` could not be prevented?

**Pull request closed without merging**
