### PR TITLE
docs: simplify installing from GitHub

### PR DESCRIPTION
**Pull request by pRizz**
Simplify the docs for installing dev from GutHub

### CODE REVIEW

**Comment by posva** [comment]
Thank you but that wouldn't be enough as it would require the user to import from `src`

**Comment by pRizz** [comment]
@posva the script still has the `npm run build` step.

`npm install vuejs/vue-router` installs `vue-router` from this GitHub repo into `node_modules`
`cd node_modules/vue-router` is the same
`npm run build` then we build in that directory

**Comment by posva** [comment]
oh, I missed that cd part. I will still have to try

**Comment by posva** [comment]
Thank you for the proposal but I think it's easier to keep a more traditional way of installing a local version

**Pull request closed without merging**
