### PR TITLE
[Doc EN]: Official Vue way to speak about a version and greater version.

### PR DESCRIPTION
**Pull request by MachinisteWeb**
Hi @posva, we have seen with @chrisvfritz a way to harmonize speaking about a version and greater version has following:

`product version` => only this version
`product version+` => this version and greater (this one replace the old `product >= version` way)

### CODE REVIEW

**Comment by posva** [comment]
Good for me but I don't see those modifications reflected on the PR 😆

**Comment by Haeresis** [comment]
https://github.com/vuejs/vue-router/pull/1841

**Comment by Haeresis** [comment]
Maintenant que tu le dis... effectivement... XD

« Voilà ! »

**Comment by MachinisteWeb** [comment]
Maintenant que tu le dis... effectivement... XD

« Voilà ! » @posva !

**Review by posva — APPROVED** [review]

**Pull request merged**
