### PR TITLE
Doc EN : Add ` on code part to consistency and comprehension

### PR DESCRIPTION
**Pull request by MachinisteWeb**
All is in title ;) It's all we have see/change for getting-started.md while our translation process.

### CODE REVIEW

**Comment by posva** [comment]
Thanks for the contribution. Since the text won't change because it's inside of a code block, I really think it's better to have them without the backticks as it makes it easier to read
WDYT @fnlctrl ?

**Comment by MachinisteWeb** [comment]
Ok but in this case that means which things like `<a>` or `to` which will be originally between « tick » which must be « without tick »because, for example, in this sentence:

```js
<!-- <router-link> will be rendered as an `<a>` tag by default -->
```

there is a lack of consitency between « &lt;router-link> » and « `<a>` »

------

Our advice is this:

```js
// short for `routes: routes`
```

is more readable than this

```js
// short for routes: routes
```

« `:` is a part of a phrase ponctuation? »

**Comment by posva** [comment]
It's true it's inconsistent and I also think that one is more readable
because it's multiples words while the other is just html
It's not a big deal and really depends on tastes, docs will be readable
either ways, so I'll let Evan decide

**Comment by MachinisteWeb** [comment]
Some others cases in all documentation and others PR (like following) tend to thinking Evan choice to also tick:

- https://github.com/vuejs/vue-ssr-docs/pull/33
- https://github.com/vuejs/vue-ssr-docs/pull/28

so let him save some time @posva ;)

**Comment by posva** [comment]
yeah, I've been merging them for some time now. Feel free to add that to other PRs as well

**Pull request merged**
