### PR TITLE
fix(hash): Properly handle encoded parameters in hash (close #2725)

### LINKED ISSUE #2725: Properly encode/decode the percentage character (% -> %25) across browsers and upon initial navigation
Currently, the percentage character creates multiple issues and inconsistencies. This is partly due to:

- the `%` is forbidden as part of the pathname in the URL per its spec (https://url.spec.whatwg.org/#path-state) if not escaped
- IE allows it because it follows a different spec (https://tools.ietf.org/html/rfc3986#section-2.4)

In Vue router, we have multiple inconsistencies between asterisk path, param paths and regular path regarding escaping these characters and whether the navigation is initial or triggered by a push/router-link

Given this set of routes in history mode

```js
[
  { path: '/foo/:p', component: Foo },
  {
    path: '*',
    component: Other,
  },
]
```

## History mode / Chrome, IE 11,10

| `to`       | route match | href produced in router-link | `$router` info after clicking | `$router` info on direct navigation         | remarks                                                                              |
| ---------- | ----------- | ---------------------------- | ----------------------------- | ------------------------------------------- | ------------------------------------------------------------------------------------ |
| `/%7D`     | `*`         | `/%7D`                       | `/%7D` - `/}`                 | `/}` - `/}`                                 | User should write `/}` as the link instead                                           |
| `/}`       | `*`         | `/%7D`                       | `/}` - `/}`                   | N/A (browser should encode it te be `/%7D`) | -                                                                                    |
| `/%25`     | `*`         | `/%25`                       | `/%25` - `/%`                 | ERROR                                       | Navigation should be possible. Should user also write `/%` to be consistent?         |
| `/%`       | `*`         | ERROR                        | N/A (not working)             | N/A (not valid)                             | Or should they escape the percent themselves because it's the only special character |
| `/foo/%7D` | `/foo/:p`   | `/%7D`                       | `/%7D` - p = `}`              | `/}` - p = `}`                              | User should write `/foo/}`                                                           |
| `/foo/}`   | `/foo/:p`   | `/%7D`                       | `/}` - p = `}`                | `/}` - p = `}`                              |
| `/foo/%25` | `/foo/:p`   | `/%25`                       | `/%25` - p = `%`              | ERROR                                       | Navigation should be possible                                                        |

## Query / TODO

---

Complete html file to test. Requires a `vue-router.js` file in the same folder

`index.html`
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>

  <body>
    <script src="https://unpkg.com/vue"></script>
    <!-- <script src="https://unpkg.com/vue-router"></script> -->
    <script src="/vue-router.js"></script>

    <div id="app">
      <pre>{{ $route.path }}</pre>
      <pre>{{ $route.params }}</pre>
      <router-link to="/">/home</router-link>
      <router-link to="/%7D">/%7D</router-link>
      <router-link to="/}">/}</router-link>
      <router-link to="/%25">/%25</router-link>
      <!-- <router-link to="/%">/%</router-link> -->
      <router-link to="/foo/%7D">/foo/%7D</router-link>
      <router-link to="/foo/}">/foo/}</router-link>
      <!-- <router-link to="/foo/%">/foo/%</router-link> -->
      <router-link to="/foo/%25">/foo/%25</router-link>
      <router-view></router-view>
    </div>

    <script>
      var Home = { template: '<div>Home</div>' }
      var Foo = { template: '<div>Foo: {{ $route.params.p }}</div>' }
      var Other = {
        template: '<div>Other: {{ $route.fullPath }}</div>',
      }
      var router = new VueRouter({
        mode: 'history',
        routes: [
          { path: '/', component: Home },
          { path: '/foo/:p', component: Foo },
          {
            path: '*',
            component: Other,
          },
        ],
      })

      new Vue({
        router: router,
        el: '#app',
      })
    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by leameow**
Fix an issue where page browsing to a route and then reloading leads to inconsistent parameters and fullPath values.

### CODE REVIEW

**Comment by posva** [comment]
hello, sorry for the delay. Do you have a reproduction for this one?

**Comment by leameow** [comment]
It relates to https://github.com/vuejs/vue-router/issues/2725, specifically, when I click a link to `#/%252520` my URL get transformed to `#/%20` and when I reload the page I get `#/` which is not correct and consistent. This fix might not be the proper fix, but we have been using this patch and didn't have issues so far.

**Comment by posva** [comment]
@isra17 can you provide an actual repro (you can use this: https://jsfiddle.net/posva/9r6xhqbp/). Also what browsers are you seeing this at? Only hash mode?

**Comment by leameow** [comment]
Can't repro injsfiddle due to URL not being visiable/modifiable. Both chrome and firefox at least. I didn't test on other mode than hash mode.

You can close the issue, I don't have my environnement with this bug anymore and I don't have the bandwith right now to dig further on this.

Cheers!

**Comment by posva** [comment]
I revisited the problem and there are a few other issues. The actual problem of double decoding affects both history and hash mode. Thanks for the case of `/%252520`, it's a good one to check double encoding!

**Pull request closed without merging**
