### PR TITLE
fix: make callback of next in beforeRouterEnter more consistent

### PR DESCRIPTION
**Pull request by zrh122**
Improve #2728. Make callback of `next` to be called as same order as `beforeRouterEnter`.

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Hi, thanks! Could you add a test for this? An e2e test should do it. You could check that a string grows to a specific value (to check the order is right) but if you have a better idea, that's good too!

**Comment by zrh122** [comment]
@posva , I will add a test for it. I intend to add the test in [navigation guards](https://github.com/vuejs/vue-router/blob/dev/test/e2e/specs/navigation-guards.js), but I find that the test code in this file never execute because it just return when find use `PhantomJS`, and currently only use `PhantomJS`.

**Comment by posva** [comment]
I see, I will take a look next week then and keep you posted. Thanks for #2749 BTW!

**Comment by posva** [comment]
As you said, it does fix #2761 too, I added a test for that. I will add another test for the other case too

**Comment by zrh122** [comment]
> As you said, it does fix #2761 too, I added a test for that. I will add another test for the other case too

Thx.

**Pull request merged**
