### PR TITLE
fix(router-view): add passing props to inactive component

### LINKED ISSUE #2301: nested props are marked as missing when changing route and using keep-alive
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/Terrijoo/pntLxf20/](https://jsfiddle.net/Terrijoo/pntLxf20/)

### Steps to reproduce
1. open console
2. click `/home`
3. click `Info`
4. click `/foo`
5. look into console

### What is expected?
The props still being "there" and no warning about the missing required prop.

### What is actually happening?
The props are apparently removed/emptied and vue throws a warning.

---
It's a combination of several circumstances:
1. `router-view` needs to be wrapped by `keep-alive`
2. props needs to be required on the component
3. prop needs to be on the children, it does work on the parent:
  - click `/home`
  - click `/foo`
  - no error/warning

### PR DESCRIPTION
**Pull request by zrh122**
Add passing `props` to inactive component. it closes #2301.

### CODE REVIEW

**Comment by posva** [comment]
@zrh122 Could you give this a new look and fix the merge conflicts please?

**Comment by zrh122** [comment]
> @zrh122 Could you give this a new look and fix the merge conflicts please?

@posva I have resolved.

**Review by posva — APPROVED** [review]
That was so fast! Thank you for the PR, it looks good, I refactored things a little bit (mostly naming) and added a few tests

**Comment by zrh122** [comment]
Thanks so much 👏.

**Pull request merged**
