### PR TITLE
Add named exports RouterLink, RouterView to es modules

### PR DESCRIPTION
**Pull request by graup**
#1976

### CODE REVIEW

**Comment by posva** [comment]
Thank you for this but I think adding the exports only for the es module is not a good idea as people don't always know which version they are using so it would be confusing not to have the export because they aren't using the right version. At the same time, if we add it to every module, it's a breaking change for common js users.

So, as said in other comments, to get the components at runtime, you call

```js
const Link = Vue.component('RouterLink')
const View = Vue.component('RouterView')
```

That's how libs like Vuetify and bootstrap-vue do as well. The router components **do not work if the plugin is not installed** anyway, so importing them in an environment where it's not sure they are installed would produce errors about `$route` and `$router` not being accessible whereas with the solution above, you can emit a custom warning for your users:

```js
const Link = Vue.component('RouterLink')
if (process.env.NODE_ENV === 'development && !Link) {
  console.warn('You should install Vue Router [link]')
}
```

**Comment by graup** [comment]
@posva thanks for taking the time to respond. I agree this solution is kind of an ugly workaround.

However, in my case the `const Link = Vue.component('RouterLink')` solution doesn't work, because I'm using several (typescript) packages. My components have explicit `Vue` imports and thus the global `Vue` class may be different, so it cannot resolve components registered in another context. Do you maybe have another idea how to solve this? It is the `<router-link>` that bites me but my real problem may be out of scope of what vue-router can do. In that case I'll gladly take it to StackOverflow.

**Comment by graup** [comment]
@posva alternatively, would you be open to a PR doing what was outlined in [this comment](https://github.com/vuejs/vue-router/issues/1976#issuecomment-374020304)?

**Comment by graup** [comment]
Looks like my issue is really caused by this: https://github.com/vuejs/vue/issues/8278

A change in vue-router wouldn't solve this anyway, so you can consider this case closed.

**Comment by posva** [comment]
Yeah, the problem about having multiple Vue imports is out of scope of vue router

> alternatively, would you be open to a PR doing what was outlined in this comment?

No, because the comment doesn't give any substantial argument. It's not required to import the router in every component test. You can easily stub the components without giving any implementation or even use global options to stub them everywhere/install globally with vue-test utils

**Pull request closed without merging**
