### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by PascalAOMS**
This is the German translation of vue-router.

- [x] Translation
- [x] Proof

### CODE REVIEW

**Comment by yyx990803** [comment]
Could you please use English in feedback/discussions? I can't read German 😂

**Comment by PascalAOMS** [comment]
I am rather new to using Git and was not aware that you would be able to see the internal discussion we had after the pull request.

It's basically about how to translate specific parts. So nothing that should concern you too much. 😅

**Comment by yyx990803** [comment]
Okay, let me know when the translation is ready to merge.

**Comment by PascalAOMS** [comment]
@yyx990803 Alright, 🇩🇪  translation is done. 🎉

**Comment by yyx990803** [comment]
@PascalAOMS sorry for late response - was in France for a week. I just merged the Russian version and now there's a small conflict, would you mind resolving it?

**Comment by PascalAOMS** [comment]
@yyx990803 Done. Git can be confusing, gosh.

**Pull request merged**
