### PR TITLE
Add wiki page docs

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Please merge this so that the people will have instant look at the docs.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks for the PR and the effort in editing the WIki, but this adds an additional place to be manually kept up-to-date when there's a version upgrade. e.g. if I update the docs in the repo but you forgot to update the Wiki, people will get confused. Ideally we want everything to be updated in one single place.

**Comment by BrainBuzzer** [comment]
I will be dedicated to update the wiki. Please merge this. And if possible make me one of the docs contributor. I loved your framework.

**Comment by yyx990803** [comment]
I appreciate your effort, but keeping docs in one place is just simpler and easier. I don't see why we need to replicate the docs in the wiki. Feel free to contribute to the docs by sending in pull requests though.

**Comment by BrainBuzzer** [comment]
OK. All right

**Pull request closed without merging**
