### PR TITLE
Removed lines causing issues with iis 10

### PR DESCRIPTION
**Pull request by hitautodestruct**
Removed the lines causing issues in windows server 2016 iis version 10.
Added more exact instructions for adding a config file.

### CODE REVIEW

**Review by posva — APPROVED** [review]
I cannot verify the information because I don't use IIS but it looks good
Thanks!

**Comment by hitautodestruct** [comment]
@posva when will this get merged into the public docs?

**Comment by posva** [comment]
I can merge it now but it won't be deployed yet anyway
edit: sorry for the close 😓

**Comment by hitautodestruct** [comment]
Hey @posva 

Will this ever be merged?

**Comment by LinusBorg** [comment]
@hitautodestruct We will, yes.

@posva We shouldn't have to wait with deployment imho, or is there a specific reason to?

**Comment by posva** [comment]
@LinusBorg Since last accident (quite some months ago) I haven't reconfigured deployment of vue-router docs, but it's something I have to do it very soon. Let's merge this and the other accepted docs PR and deploy. If you have everything setup for the deploy, ping me on slack so I know I don't have to deploy 🙂

**Pull request merged**
