### PR TITLE
Add warning unknown route

### PR DESCRIPTION
**Pull request by staskjs**
Add warning about not existing route, because "Cannot read property 'path' of undefined" is really not informative.

### CODE REVIEW

**Comment by posva** [comment]
Thanks for this!
Can you please surround the warn with a check like https://github.com/vuejs/vue-router/blob/0e319d44102a8ebc07c8a41c437530d86c4b0a73/src/create-route-map.js#L31 and add a test?

**Comment by staskjs** [comment]
OFFTOPIC: Does owner receive notifications about adding commits to pull request?

In case of not, done.

**Review by fnlctrl — APPROVED** [review]

**Comment by LinusBorg** [comment]
> Does owner receive notifications about adding commits to pull request?

Nope, no notification. Commenting like you did is a good practice.

**Comment by posva** [comment]
I did receive a notification for your commit

**Comment by LinusBorg** [comment]
Oh... ^^

**Comment by posva** [comment]
Thanks @LinusBorg 😆

**Pull request merged**
