### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by ghost**
Fix (comment) for transition issue

### CODE REVIEW

**Comment by posva** [comment]
What are you trying to improve in the examples. What wasn't clear?

**Comment by ghost** [comment]
```
let to.path = '/someroute/'; // if we are coming back from deeper route, check this trailing slash
let from.path = '/someroute/something';
const toDepth = to.path.split('/').length // 3 | ["", "example", ""]
const fromDepth = from.path.split('/').length // 3 | ["", "example", "something"]
this.transitionName = toDepth < fromDepth ? 'slide-right' : 'slide-left' // will be false as a result slide-left, but we expect it to be slide-right
```

**Comment by posva** [comment]
I'd appreciate a bit more communication with sentences 😅

**Comment by ghost** [comment]
Sorry :) My english isn't perfect :) I'm working right now on mobile vue app. And had an issue with this example. Becouse when you go back from a child route to parent you will have a trailing slash and this example logic will not work. This why I wrote this comment.

**Comment by posva** [comment]
No worries!
Thanks for the PR but I think it will be better to note in docs that the trailing slash is removed by default but that it can be controlled by passing options to path-to-regexp (`strict: true`) 🙂

**Pull request closed without merging**
