### PR TITLE
Added VueRouter.version

### PR DESCRIPTION
**Pull request by ytbryan**

### CODE REVIEW

**Comment by posva** [comment]
files in the dist directory are generated files, nothing should be added there. Also, it shouldn't start with a `v`
@fnlctrl Adding the version looks legit but we should add it to vuex as well to be consistent. WDYT?
@yyx990803 Shouldn't this https://github.com/vuejs/vue/blob/dev/src/core/index.js#L11 be added with a replace plugin, using something like `__VERSION__` and then, in the rollup file, read the version from the package? This'd only work if the package is updated **before** bundling.

**Comment by fnlctrl** [comment]
Yeah, maybe we should add versions to vuex/vue-router..

**Comment by yyx990803** [comment]
@posva yes - both suggestions make sense. PR welcome.

**Comment by posva** [comment]
@yyx990803 Ok, will do

**Comment by posva** [comment]
@yyx990803 Actually, there's already a manual replacement done with a regex in vue to support another version for weex aswell.
I was thinking about using https://github.com/rollup/rollup-plugin-replace. I'll do so for vue-router and vuex.

**Comment by posva** [comment]
Thanks for the suggestion @ytbryan 😉 
Closing this in favor of #991

**Pull request closed without merging**
