### PR TITLE
Update route.js

### PR DESCRIPTION
**Pull request by lzxb**
Feat route.search
```javascript
export default {
 ///... options
 watch: {
   '$route.search' () {
     // update data
   }
 }
}
```

### CODE REVIEW

**Comment by posva** [comment]
What feature are you trying to add that Vue doesn't have?

**Comment by lzxb** [comment]
Yes, but this submission seems to be a bug

**Comment by posva** [comment]
What are you trying to add with that search property? It looks like the `hash` property
If you have a bug please, open an issue with a repro

**Comment by lzxb** [comment]
It's the same thing as $route.query, but sometimes it takes the form of a string

**Comment by posva** [comment]
Thanks for the pr, but we'll pass on this for the moment. You can open a new issue explaining the feature request if you want but I don't feel as if this is something we need.

**Comment by lzxb** [comment]
Because $ruote.query is a reference type, when I store a $ruote.query, when I switch back different routes back, then I compare the stored $ruote.query with the current $ruote.query and return the false. When using $ruote.search, it won't fail because it is a string type comparison

**Comment by posva** [comment]
In that case you can compare both queries converting them into strings
first. Just in case, you should not modify the query object because the
$route object is immutable

**Comment by lzxb** [comment]
```javascript
{
  // ... options
  created () {
    this.$router.replace({ query: { test: new Date().getTime() } })
    console.log('ok')
  },
  watch: {
    $route: {
      deep: true,
      handler: function (to, from) {
        console.log(to, from, to.query === from.query) // query change
        // $route.search It's actually converting $route.query into strings
      }
    }
  }
}
```

**Comment by posva** [comment]
You should use an object comparison function in your case.

**Pull request closed without merging**
