### PR TITLE
fix(router-view): register instance in init hook (fix #2561)

### LINKED ISSUE #2561: beforeRouteEnter hook's cb is not called (same component across diffrent routes and keep-alive applied )
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/9vctongd/1/](https://jsfiddle.net/9vctongd/1/)

### Steps to reproduce
1. open the JSFiddle provided, open the console
2. click link GO TO FOO1
3. click link GO TO BAR
4. click link GO TO FOO2

### What is expected?
console prints:

foo enter

foo enter cb

foo enter

foo enter cb

### What is actually happening?
console prints:

foo enter

foo enter cb

foo enter

---
also results in an infinite function call (function poll in base.js)

### PR DESCRIPTION
**Pull request by zrh122**
close #2561

### CODE REVIEW

**Comment by posva** [comment]
Hey could you add a test for this?

An e2e test should do it

**Comment by zrh122** [comment]
Yes, i will.

**Comment by zrh122** [comment]
@posva , e2e test added.

**Review by posva — COMMENTED** [review]
Thanks, I'm merging this locally after applying some modifications (splitting the e2e test to keep the navigation guard one in an existing e2e test and the keep alive in another

**Comment by posva** [comment]
Merged locally!

**Comment by zrh122** [comment]
@posva  the e2e test for #2561 may be not correct. I removed the code ([register instance in init hook](https://github.com/vuejs/vue-router/blob/5ad453995bd1d9259e058d4b1ad6428e825255da/src/components/view.js#L77)), and executed `npm run test:e2e`, all the test case was passed. It should not be passed as i expect.

mine:
```javascript
// routes
[
  // foo1
  { path: '/foo1', component: Foo },

  // foo2, same component as foo1
  { path: '/foo2', component: Foo },

  // bar
  { path: '/bar', component: Bar }
]
```
click order: `/foo1` -> `/bar` -> `/foo2`

yours:
```javascript
// routes
[  
  {
    path: '/with-guard1',
    name: 'with-guard1',
    component: WithGuard
  },
  {
    path: '/with-guard2',
    name: 'with-guard2',
    component: WithGuard
  }
]
```
click order: `/with-guard1` -> `/with-guard2` -> `/with-guard1`

maybe you can add another route, and the click order can be:

 `/with-guard1` -> `/another` -> `/with-guard2`

**Comment by posva** [comment]
Right! Thanks for checking, I'm going to fix the test

**Pull request closed without merging**
