### PR TITLE
docs: typo in node.js example

### PR DESCRIPTION
**Pull request by Steven-Chang1114**
It appears in https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations as the index.html is mistyped as index.htm in the Native Node.js section

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Thanks, can you remove the package-lock file please?

**Comment by Steven-Chang1114** [comment]
> Thanks, can you remove the package-lock file please?

Of course! was wondering why it falis the deployment check.

**Review by posva — APPROVED** [review]
Thanks!

**Comment by Steven-Chang1114** [comment]
Cheers, thank you for merging!

**Pull request merged**
