### PR TITLE
router-link exact path matching (#fix 2040)

### PR DESCRIPTION
**Pull request by samgre**
There have been at least two requests (#2040 and #2193) for adding ability to match only the path in a router-link.

A use case is highlighted in the issue #2040. Sometimes you want to highlight a router-link regardless of the query string parameters. This happens e.g. with paginated listing pages, where the desired page number is often supplied as a query string parameter.

This pull requests implements the requested feature.

### CODE REVIEW

**Comment by samgre** [comment]
Thanks @CurtisBelt for notifying me. Made the pull request!

**Comment by posva** [comment]
Note to myself: having a long list of classes is quite confusing, maybe we should refactor this in some kind of string based prop and an object of classes in config like `linkClasses`

**Comment by JulienTant** [comment]
Any news on this PR ?

**Comment by 1337huania** [comment]
Waiting for this PR too... Is there any news?

**Comment by MariaSMM** [comment]
Hey guys, have you got any solutions?

**Comment by Djaler** [comment]
What about it?

**Comment by gaofeng0630** [comment]
？？？？

**Pull request closed without merging**
