### PR TITLE
docs(guide): add warning for multipage apps

### LINKED ISSUE #3537: Example server configurations only work for single page apps
### Version
3.5.1

### Reproduction link
[https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations)

### Steps to reproduce
The [example server configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) in the Vue Router documentation only work for single page apps, not [multipage apps](https://cli.vuejs.org/guide/html-and-static-assets.html#building-a-multi-page-app).

### What is expected?
The server should return the correct html content for the specific page requested from a multipage app.

### What is actually happening?
The server returns unexpected and incorrect content when the user tries to navigate to other pages in a multipage app.

---
I recommend adding a note to the documentation warning that multipage apps may require more sophisticated server configuration. An example would be helpful, but not necessary.

### PR DESCRIPTION
**Pull request by Blakelist7**
Close #3537

### CODE REVIEW

**Comment by posva** [comment]
Thank you but I don't think this bring any value for someone looking for help

**Comment by Blakelist7** [comment]
@posva could you help how can I modify it ?
Should add some example?

**Comment by posva** [comment]
An example is necessary for this make any sense and I don't think it's helpful to say things need to be more sophisticated like the issue was saying. Feel free to drop it if things aren't clear, the initial issue wasn't clear

**Comment by Blakelist7** [comment]
@posva and one more thing that whenever I ran npm run commit it showed there is no script named commit .
I checked it and there was no script.
Screenshot from 2021-05-02 22-07-13

**Comment by posva** [comment]
you should do `git commit`

**Comment by Blakelist7** [comment]
ok 
but then what is the use of `npm run commit`

**Comment by posva** [comment]
I don't know why you are running that

**Comment by Blakelist7** [comment]
just to test it

**Comment by Blakelist7** [comment]
@posva Hey, we should remove `npm run commit` if there is no use of it from contributing guide .
https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md

**Comment by posva** [comment]
Sure! Can you open a PR?

**Comment by Blakelist7** [comment]
On it.

**Pull request closed without merging**
